apiVersion: v1
kind: Service
metadata:
  name: gin-api-service
  namespace: cyber-dashboard
  labels:
    app: gin-api
    component: backend
    tier: api
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: gin-api