apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: cyber-dashboard
  labels:
    app: fastapi
    component: backend
    tier: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
        component: backend
        tier: api
    spec:
      containers:
      - name: fastapi
        image: dulc3/command-be-py:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: PORT
          value: "8000"
        - name: ENVIRONMENT
          value: "production"
        - name: OPENWEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: fastapi-secrets
              key: openweather-api-key
              optional: true
        - name: ALLOWED_ORIGINS
          value: "https://command.dulc3.tech,http://localhost:3000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /app/cache
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      restartPolicy: Always
      securityContext:
        fsGroup: 1000