apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: cyber-dashboard
  labels:
    app: fastapi
    component: backend
    tier: api
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: fastapi